Nodegroup taints support
selectel/mks-go pull request #50
Opened 2020-08-31 13:32 UTC by dstdfx

For #49

2020-08-31 14:22 UTC, ozerovandrei requested changes

2020-08-31 14:22 UTC, ozerovandrei commented on pkg/v1/cluster/testing/fixtures.go
> +		        ]
Bad indent.

2020-08-31 14:25 UTC, kolsean commented on pkg/v1/cluster/doc.go
> +            {
Let's use two spaces for indentation here in line with other examples.

2020-08-31 14:25 UTC, kolsean commented on pkg/v1/cluster/doc.go
> +        },
extra `},` can be removed

2020-08-31 14:28 UTC, kolsean requested changes
fix doc

2020-08-31 19:26 UTC, ozerovandrei requested changes

2020-08-31 19:26 UTC, ozerovandrei commented on pkg/v1/nodegroup/testing/fixtures.go
> +       ]
Bad indent.

2020-08-31 21:21 UTC, kolsean requested changes

2020-08-31 21:21 UTC, kolsean commented on pkg/v1/cluster/doc.go
> +                Effect: nodegroup.NoScheduleEffect,
It would be great to use two spaces here too.

2020-09-01 08:12 UTC, ozerovandrei approved these changes
👍

2020-09-01 08:40 UTC, kolsean approved these changes
LGTM!

2020-09-01 08:43 UTC, merged