Cluster V1: added feature gates & admission controllers at kubernetes options
selectel/mks-go pull request #55
Opened 2021-01-11 11:15 UTC by pavelpereyma

Added feature gates and admission controllers to cluster kubernetes options.

2021-01-11 18:41 UTC, kolsean requested changes
Looks good, but there are some formatting notes.

2021-01-11 18:41 UTC, kolsean commented on pkg/v1/cluster/schemas.go
> +	// FeatureGates represents feature gates that should be enabled.
Please add a blank line before the comment similar to the code style used in the package.
This remark applies for this and the following comment.

2021-01-11 18:41 UTC, kolsean commented on pkg/v1/cluster/testing/fixtures.go
> +			"feature_gates": [
Let's use spaces for indentation here and in other similar pieces below. Tab characters break format of these JSON fixtures a little. You can view it more clearly using `git log -1 -p` command.

2021-01-11 18:41 UTC, kolsean commented on pkg/v1/cluster/testing/fixtures.go
> +			]
Extra spaces  after `]` character here and below.

2021-01-11 18:41 UTC, kolsean commented on pkg/v1/cluster/testing/fixtures.go
> +			]
and here.

2021-01-11 18:41 UTC, kolsean commented on pkg/v1/cluster/testing/fixtures.go
> +			]        }
Apart from the extra tabs I guess the line break is missing after `]`

2021-01-12 13:52 UTC, pavelpereyma commented
Thanks for review. I updated formatting for docs and some code style.

2021-01-13 10:03 UTC, kolsean approved these changes
LGTM

2021-06-15 13:24 UTC, merged